Repository hanataba227/HackLLM, pull requests merged in 2025-05, with the labels that each got.

#2 템플릿 파일 생성
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
  .github/pull_request_template.md
Labels: documentation

#10 ctf08 프롬프트 수정, .txt 파일 업로드 기능 추가
  app.py
  data/ctf08.txt
  pages/ctf07.py
  pages/ctf08.py
  utils/llm_utils.py
  utils/ui.py
Labels: 개선

#22 ctf02.py 문제 제작, 프롬프트 수정, 시나리오 작성
  llm_manual/SCENARIO_02.md
  pages/ctf02.py
  utils/llm_utils.py
Labels: 문서화, 개선

#25 CTF05 문제 생성, 프롬프트 수정
  pages/ctf05.py
  utils/llm_utils.py
Labels: 개선

#27 프롬프트 수정, LLM 모델 추가
  app.py
  data/ctf1.csv
  pages/ctf01.py
  requirements.txt
  utils/llm_utils.py
  utils/ui.py
Labels: 개선

#30 llm_utils.py ctf03_LLM_ask함수 수정
  app.py
  pages/ctf03.py
  utils/llm_utils.py
  utils/mathlib.py
  utils/mathlib2.py
Labels: 개선

#36 Ctf06 설명, .md, 프롬프트 수정
  llm_manual/SCENARIO_06.md
  pages/ctf06.py
  utils/llm_utils.py
Labels: 문서화, 개선

#39 [CTF04] CSV 업로드 기능 추가 및 오염 프롬프트 기반 LLM 응답 구현
  data/real.csv
  llm_manual/SCENARIO_04.md
  pages/ctf04.py
  utils/llm_utils.py
Labels: 문서화, 개선

#41 Ctf06의 프롬프트와 .md파일 수정
  llm_manual/SCENARIO_06.md
  utils/llm_utils.py
Labels: 버그, 문서화, 개선

#47 [CTF09] misinformation 시나리오 전체 수정
  pages/ctf09.py
  utils/llm_utils.py
Labels: 개선

#48 ctf09 제목 추가 및 requirements.txt 제거
  app.py
  requirements.txt
Labels: 개선

#49 SCENARIO_03 작성
  llm_manual/SCENARIO_03.md
Labels: 문서화

#64 ctf09 gpt 모델 변경
  utils/llm_utils.py
Labels: 버그

#76 Ctf01 재업로드
  data/ctf01.csv
  llm-test-10.yaml
  llm_manual/SCENARIO_01.md
  pages/ctf01.py
  utils/llm_utils.py
Labels: 문서화, 개선

#79 api 키 입력받는 기능 추가
  llm-test-10.yaml
  pages/ctf01.py
  pages/ctf02.py
  pages/ctf03.py
  pages/ctf04.py
  pages/ctf05.py
  pages/ctf06.py
  pages/ctf07.py
  pages/ctf08.py
  pages/ctf09.py
  pages/ctf10.py
  pages/login.py
  pages/mypage.py
  utils/api_key.py
  utils/auth.py
  utils/llm_utils.py
Labels: 개선
