Repository hanataba227/HackLLM, pull requests merged in 2025-07, with the labels that each got.

#121 ctf03
  utils/llm_utils.py
  utils/mathlib.py
  utils/mathlib2.py
Labels: 개선

#128 Ctf06 dev
  pages/ctf06.py
  utils/llm_utils.py
Labels: 개선

#129 시나리오 명 수정
  pages/ctf09.py
Labels: 개선

#130 시나리오 명 변경 및 CTF 09 시스템 프롬포트 수정
  app.py
  pages/ctf09.py
Labels: 개선

#141 첫 로그인시 api 키 미제출로 뜨는 오류 수정
  pages/mypage.py
Labels: 개선

#144 Ctf03 시나리오에 mathlib mathlib2 내용추가
  pages/ctf03.py
Labels: 개선

#147 [CTF01] dev에 최신 코드로
  app.py
  pages/ctf01.py
  utils/llm_utils.py
  utils/ui.py
Labels: 개선

#148 hint1,hint2 숨기기
  pages/ctf04.py
Labels: 개선

#149 [CTF01] 결제, 주문 시나리오 플래그 조건 수정
  pages/ctf01.py
Labels: 개선

#150 Dev db api
  pages/mypage.py
Labels: 개선

#158 Ctf05 html 다운로드 수정 및 프롬프트 수정
  llm-test-10.yaml
  pages/ctf05.py
  requirements.txt
  utils/llm_utils.py
Labels: 개선

#161 ctf08 프롬프트 수정
  utils/llm_utils.py
Labels: 개선

#162 Code
  utils/llm_utils.py
Labels: 개선

#163 Ctf 09 시나리오 수정
  llm_manual/SCENARIO_09.md
Labels: 개선

#165 Ctf07
  llm-test-10.yaml
  pages/ctf07.py
  utils/llm_utils.py
Labels: 개선

#167 Ctf07
  app.py
  pages/ctf07.py
  pages/edu07.py
  utils/llm_utils.py
  utils/ui.py
Labels: 개선

#168 Ctf06 dev
  llm-test-10.yaml
  pages/ctf06.py
  utils/llm_utils.py
Labels: 개선

#173 [Chore] 매뉴얼 형식 통일 및 최신 내용으로 재작성
  llm_manual/SCENARIO_01.md
  llm_manual/SCENARIO_02.md
  llm_manual/SCENARIO_03.md
  llm_manual/SCENARIO_04.md
  llm_manual/SCENARIO_05.md
  llm_manual/SCENARIO_06.md
  llm_manual/SCENARIO_07.md
  llm_manual/SCENARIO_08.md
  llm_manual/SCENARIO_09.md
  llm_manual/SCENARIO_10.md
Labels: 문서화, 개선

#174 flag 출력 오류 해결
  pages/ctf06.py
  pages/ctf07.py
  utils/llm_utils.py
Labels: 개선

#177 Ctf 05 최종 수정
  llm_manual/SCENARIO_05.md
  llm_manual/SCENARIO_09.md
  pages/ctf05.py
  utils/llm_utils.py
Labels: 개선

#178 ctf02_시스템 프롬프트 줄임
  utils/llm_utils.py
Labels: 개선

#181 De from gpt 디자인 수정
  app.py
  pages/ctf02.py
  pages/ctf03.py
  pages/ctf04.py
  pages/ctf05.py
  pages/ctf06.py
  pages/ctf07.py
  pages/ctf08.py
  pages/ctf09.py
  pages/ctf10.py
  pages/edu00.py
  pages/edu01.py
  pages/edu02.py
  pages/edu03.py
  pages/edu04.py
  pages/edu05.py
  pages/edu06.py
  pages/edu07.py
  pages/edu08.py
  pages/edu09.py
  pages/edu10.py
  pages/login.py
  static/styles.css
  utils/ui.py
Labels: 개선

#182 Sch
  app.py
  pages/ctf02.py
  pages/ctf03.py
  pages/ctf04.py
  pages/ctf05.py
  pages/ctf06.py
  pages/ctf07.py
  pages/ctf08.py
  pages/ctf09.py
  pages/ctf10.py
  pages/edu00.py
  pages/edu01.py
  pages/edu02.py
  pages/edu03.py
  pages/edu04.py
  pages/edu05.py
  pages/edu06.py
  pages/edu07.py
  pages/edu08.py
  pages/edu09.py
  pages/edu10.py
  pages/login.py
  static/styles.css
  utils/llm_utils.py
  utils/ui.py
Labels: 개선

#186 Dev cache 캐시 적용
  utils/api_key.py
  utils/auth.py
  utils/llm_utils.py
Labels: 개선

#190 Ctf04
  pages/ctf04.py
  utils/llm_utils.py
  utils/rag_utils_supabase.py
Labels: 개선

#195 다크모드 기능 추가
  app.py
  pages/edu01.py
  pages/edu02.py
  pages/edu03.py
  pages/edu04.py
  pages/edu05.py
  pages/edu06.py
  pages/edu07.py
  pages/edu08.py
  pages/edu09.py
  pages/edu10.py
  static/styles.css
Labels: 개선

#193 [문서] ctf04 최신화에 따른 매뉴얼 업데이트
  llm_manual/SCENARIO_04.md
Labels: 문서화

#282 readme 수정
  README.md
Labels: 문서화

#283 readme 수정
  README.md
  llm_manual/SCENARIO_04.md
  llm_manual/SCENARIO_05.md
Labels: 문서화

#285 종속성 수정
  llm-test-10.yaml
  requirements.txt
Labels: 개선

#286 종속성 제거
  llm-test-10.yaml
  requirements.txt
Labels: 개선
