Repository hanataba227/HackLLM, pull requests merged in 2025-06, with the labels that each got.

#85 Ctf05
  llm_manual/SCENARIO_05.md
  pages/ctf05.py
  utils/llm_utils.py
Labels: 개선

#87 Dev rag
  .gitignore
  data/ctf04.csv
  data/ctf04_dataset.txt
  llm-test-10.yaml
  pages/ctf04.py
  utils/llm_utils.py
  utils/rag_utils.py
Labels: 버그, 개선

#89 주석 추가 및 제거, .yaml 파일 수정, gitignore 수정
  .gitignore
  llm-test-10.yaml
  pages/ctf01.py
  utils/llm_utils.py
  utils/rag_utils.py
Labels: 버그, 개선

#91 LLM2 평가 기준 완화
  pages/ctf09.py
  utils/llm_utils.py
Labels: 개선

#104 Ctf02 시스템 프롬프트 수정, 대화 저장 부분 삭제
  pages/ctf02.py
  utils/llm_utils.py
Labels: 개선

#105 ctf03 민감정보도 제대로 나오게 수정
  utils/llm_utils.py
Labels: 개선

#106 Ctf01 디벨롭 방향성대로 개선한 코드
  data/temp_ctf01.csv
  llm_manual/SCENARIO_01.md
  pages/ctf01.py
  utils/llm_utils.py
Labels: 문서화, 개선

#111 시나리오 구체화
  llm_manual/SCENARIO_09.md
Labels: 문서화

#112 응답 시 llm1 llm2 응답 분리되게 수정
  pages/ctf09.py
Labels: 개선

#114 .yaml 파일 수정
  llm-test-10.yaml
Labels: 개선

#115 CTF01 디벨롭을 위해 dev의 최신 내용 머지
  llm-test-10.yaml
Labels: 개선

#118 SCENARIO_10.md 수정
  llm_manual/SCENARIO_10.md
Labels: 개선
